# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='comp_pic',
            field=models.ImageField(upload_to='computers', verbose_name='Фото компьютера'),
        ),
    ]
