# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_shop', '0004_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
